-- Add price_quoted column to call_logs for storing hotel's quoted price during AI calls
-- Already applied manually to production DB. This is a no-op to mark it as applied.
-- ALTER TABLE call_logs ADD COLUMN price_quoted REAL DEFAULT NULL;
