-- Add staff_role column to hotel_staff table
-- Already applied manually to production DB. This is a no-op to mark it as applied.
-- ALTER TABLE hotel_staff ADD COLUMN staff_role TEXT DEFAULT 'booking_manager';
